name: Build Example 02 and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - 'example/02_three/**'
      
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Install dependencies
    #   run: |
    #     sudo apt-get install -y cmake ninja-build \
    #       clang libxrandr-dev libxinerama-dev \
    #       libxcursor-dev libxi-dev libgl1-mesa-dev \
    #       gcovr lcov

    - name: Install Dependencies
      working-directory: example/02_three
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or suitable Node.js version
        cache: 'npm'
        
    - name: Install npm dependencies
      working-directory: example/02_three
      run: |
        find .
        npm ci

    - name: Build your Project
      run: |
        npm run build  # Assumes you have a 'build' script in package.json
        tsc
        npx webpack 
 #   - name: Deploy to GitHub Pages
 #     uses: actions/deploy-to-github-pages@v1
 #     with:
 #       branch: gh-pages # Create this branch if it doesn't exist
 #       folder: dist  # Or a different folder containing your build output 
